name: Bug Report
description: Report an issue with the Agent365 Python SDK.
title: "[BUG] - [short description]"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Thank you for reporting a bug in the Agent365 Python SDK! Please fill out the following information to help us diagnose and fix the issue.

  - type: input
    attributes:
      label: "Bug Description"
      description: "Provide a clear and concise description of the bug."
      placeholder: "e.g., Agent runtime throws TypeError when processing tool responses, or observability module fails to emit telemetry events."
      required: true

  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the behavior. Include code snippets if possible."
      placeholder: |
        e.g., 
        1. Import microsoft_agents_a365.runtime
        2. Create an agent with custom tools
        3. Call agent.process_activity() with a specific message
        4. Observe error in console
      value: |
        1. 
        2. 
        3. 
      required: true

  - type: textarea
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "e.g., The agent should process the tool response and return a successful activity without errors."
      required: true

  - type: textarea
    attributes:
      label: "Actual Behavior"
      description: "What actually happened? Include error messages, stack traces, or unexpected output."
      placeholder: |
        e.g., 
        TypeError: 'NoneType' object is not subscriptable
        File "microsoft_agents_a365/runtime/agent.py", line 123, in process_activity
      required: true

  - type: dropdown
    attributes:
      label: "Affected SDK Component"
      description: "Which Agent365 SDK package is affected?"
      options:
        - microsoft-agents-a365-runtime
        - microsoft-agents-a365-tooling
        - microsoft-agents-a365-observability-core
        - microsoft-agents-a365-observability-extensions-langchain
        - microsoft-agents-a365-observability-extensions-openai
        - microsoft-agents-a365-observability-extensions-semantickernel
        - microsoft-agents-a365-tooling-extensions-agentframework
        - microsoft-agents-a365-tooling-extensions-azureaifoundry
        - microsoft-agents-a365-tooling-extensions-openai
        - microsoft-agents-a365-tooling-extensions-semantickernel
        - microsoft-agents-a365-notifications
        - Not sure / Multiple components
      required: true

  - type: input
    attributes:
      label: "SDK Version"
      description: "What version of the Agent365 SDK are you using? (Run: pip show microsoft-agents-a365-runtime)"
      placeholder: "e.g., 0.1.0 or 0.1.0.dev5"
      required: true

  - type: input
    attributes:
      label: "Python Version"
      description: "What version of Python are you using? (Run: python --version)"
      placeholder: "e.g., Python 3.11.5 or Python 3.12.0"
      required: true

  - type: dropdown
    attributes:
      label: "Operating System"
      description: "What operating system are you running on?"
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (other distribution)
        - Azure (Container Apps / App Service)
        - Other
      required: true

  - type: textarea
    attributes:
      label: "Environment Details"
      description: "Additional environment information (virtual environment, container, cloud service, etc.)"
      placeholder: |
        e.g., 
        - Running in Docker container
        - Deployed on Azure Container Apps
        - Using venv virtual environment
        - Running in GitHub Codespaces
      required: false

  - type: textarea
    attributes:
      label: "Code Sample (Optional)"
      description: "Provide a minimal code sample that reproduces the issue."
      placeholder: |
        ```python
        from microsoft_agents_a365.runtime import Agent

        # Your code here that reproduces the bug
        agent = Agent(...)
        ```
      required: false

  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Add any other context, logs, stack traces, or screenshots that might help."
      placeholder: |
        e.g., 
        - Full stack trace
        - Relevant log output
        - Related issues or discussions
        - Workarounds attempted
      required: false

  - type: checkboxes
    attributes:
      label: "Impact"
      description: "How does this bug affect your work?"
      options:
        - label: Blocks development completely
        - label: Blocks specific feature implementation
        - label: Has a workaround but impacts productivity
        - label: Minor issue with minimal impact
