name: Feature Request
description: Suggest a new feature or improvement for the Agent365 Python SDK.
title: "[FEATURE] - [short description]"
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Thank you for suggesting a feature for the Agent365 Python SDK! Please fill out the following template to help us evaluate your request.

  - type: input
    attributes:
      label: "Feature Description"
      description: "Describe the feature or enhancement you would like to see in the Agent SDK."
      placeholder: "e.g., Add support for streaming responses in the observability module, or support for custom authentication providers."
      required: true

  - type: textarea
    attributes:
      label: "Use Case"
      description: "What problem does this feature solve or how would it improve agent development?"
      placeholder: "e.g., Streaming responses would allow real-time monitoring of agent interactions in production, improving debugging capabilities for long-running agents."
      required: true

  - type: dropdown
    attributes:
      label: "Affected SDK Component"
      description: "Which part of the Agent365 SDK would this feature affect?"
      options:
        - microsoft-agents-a365-runtime
        - microsoft-agents-a365-tooling
        - microsoft-agents-a365-observability-core
        - microsoft-agents-a365-observability-extensions
        - microsoft-agents-a365-tooling-extensions
        - microsoft-agents-a365-notifications
        - Documentation
        - Multiple components
        - Other (specify in additional context)
      required: true

  - type: input
    attributes:
      label: "Potential Impact"
      description: "How would this feature impact agent development or the developer experience?"
      placeholder: "e.g., Would reduce development time by 30% for implementing observability in production agents."
      required: true

  - type: dropdown
    attributes:
      label: "Priority"
      description: "How important is this feature to your agent development workflow?"
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current development
        - Critical - Prevents SDK adoption
      required: true

  - type: textarea
    attributes:
      label: "Proposed Solution (Optional)"
      description: "If you have ideas on how this feature could be implemented, please share them."
      placeholder: "e.g., Could add a StreamingObserver class that implements the Observer pattern for real-time event callbacks."
      required: false

  - type: textarea
    attributes:
      label: "Alternative Solutions Considered"
      description: "Have you considered any workarounds or alternative approaches?"
      placeholder: "e.g., Currently using custom logging, but it doesn't integrate with the SDK's observability framework."
      required: false

  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Add any other information that might be helpful (code examples, related issues, external resources)."
      placeholder: "e.g., Related to #123, similar to feature in Microsoft.Agents .NET SDK, or example code showing the desired API."
      required: false
